name: cc2025-server

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: cc2025-server:latest
    container_name: CC2025Server
    restart: on-failure
    env_file:
      - .env-production
    ports:
      - 8080:8080
    depends_on:
      - mongo-database
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
    volumes:
      - ./certificates:/app/certificates

  mongo-database:
    image: mongo:6.0
    container_name: CC2025Database
    restart: on-failure
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - ./scripts/mongo-init:/docker-entrypoint-initdb.d:ro
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M

  seq:
    image: datalust/seq:latest
    container_name: Seq
    restart: on-failure
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=${SEQ_FIRSTRUN_ADMINPASSWORD}
    volumes:
      - seq-data:/data

volumes:
  mongo-data:
  seq-data:
